/// Audio watermark embedding and extraction pipeline.
///
/// Orchestrates the full encode/decode round-trip: encrypt → tone-encode →
/// embed into host audio → extract → decode → decrypt. Operates entirely
/// in memory on normalised double arrays; WAV file I/O is handled
/// separately by [WavUtils].
library;

import 'dart:typed_data';

import 'package:encrypt/encrypt.dart';

import '../dsp/aes_crypto.dart';
import '../dsp/crc.dart';
import '../dsp/decoder.dart';
import '../dsp/protocol.dart';
import '../dsp/tone_generator.dart';
import '../dsp/tuning_config.dart';

class Embedder {
  /// Mixes [watermarkSamples] (already generated by [ToneGenerator] at
  /// [watermarkAmplitude]) into [hostSamples] by simple addition, starting
  /// at [offset] (default 0).
  ///
  /// Throws [ArgumentError] if the host array is too short to hold the
  /// watermark samples starting at the given offset.
  ///
  /// After mixing, clips the result to [-1.0, 1.0] to avoid clipping
  /// artifacts if the host song is already near full scale.
  static List<double> embed(
    List<double> hostSamples,
    List<double> watermarkSamples, {
    int offset = 0,
  }) {
    if (offset < 0) {
      throw ArgumentError.value(offset, 'offset', 'must not be negative');
    }
    if (watermarkSamples.length > hostSamples.length - offset) {
      throw ArgumentError(
        'Host audio is too short to hold the watermark at offset $offset. '
        'Need ${offset + watermarkSamples.length} samples, '
        'but host has only ${hostSamples.length}.',
      );
    }

    // Copy host and mix in the watermark
    final mixed = List<double>.from(hostSamples);
    for (int i = 0; i < watermarkSamples.length; i++) {
      mixed[offset + i] = (mixed[offset + i] + watermarkSamples[i])
          .clamp(-1.0, 1.0);
    }
    return mixed;
  }

  /// Convenience wrapper for the full embedding pipeline.
  ///
  /// Takes a [message] string, a [key], and [hostSamples]; encrypts with
  /// AES-128-CTR (Stage 1), appends a CRC-8 checksum (Stage 10), converts
  /// to bits (Stage 2), generates tone samples with the redundant length
  /// header via [ToneGenerator.bitsToSamplesWithHeader], and embeds into
  /// the host at [offset].
  ///
  /// Returns the mixed sample array.
  static List<double> embedMessage(
    String message,
    Key key,
    List<double> hostSamples, {
    int offset = 0,
  }) {
    final ciphertext = WatermarkCrypto.encrypt(message, key);
    final protectedPayload = Crc8.appendChecksum(ciphertext);
    final payloadBits = ToneGenerator.bytesToBits(protectedPayload);
    final watermarkSamples =
        ToneGenerator.bitsToSamplesWithHeader(payloadBits);
    return embed(hostSamples, watermarkSamples, offset: offset);
  }

  /// Inverse convenience wrapper: extracts and decrypts a message from
  /// [mixedSamples].
  ///
  /// Scans the entire sample array for a preamble (using
  /// [Decoder.findPreambleEndFrom]), then decodes the length-prefixed
  /// payload, converts bits back to bytes, verifies the trailing CRC-8
  /// checksum, and decrypts with AES-128-CTR.
  ///
  /// Returns the original message string, or `null` if no valid
  /// preamble/message is found or if checksum verification fails.
  static String? extractMessage(List<double> mixedSamples, Key key) {
    try {
      // Search the whole array for the preamble
      final preambleEnd = Decoder.findPreambleEndFrom(mixedSamples, 0);
      if (preambleEnd == null) {
        return null;
      }

      // Decode starting from the end of the preamble
      final afterPreamble = mixedSamples.sublist(preambleEnd);

      // Read redundant header (3 × 8 bits = 24 bits)
      final rawHeaderBits = Decoder.readBits(afterPreamble, 24);
      final byteLength = Decoder.majorityVoteHeader(rawHeaderBits);

      if (byteLength <= 1 || byteLength > 255) {
        return null;
      }

      // Calculate number of samples for the 24-bit header
      final symbolSamples =
          (sampleRate * TuningConfig.symbolDurationMs / 1000).round();
      final payloadStart = 24 * symbolSamples;

      // Read payload bits
      final payload = afterPreamble.sublist(payloadStart);
      final payloadBits = Decoder.readBits(payload, byteLength * 8);

      // Convert bits → bytes → verify CRC-8
      final rawBytesWithChecksum = ToneGenerator.bitsToBytes(payloadBits);
      final verifiedCiphertext = Crc8.verifyAndExtract(rawBytesWithChecksum);

      if (verifiedCiphertext == null) {
        // Checksum mismatch — signal corrupted in acoustic channel
        return null;
      }

      return WatermarkCrypto.decrypt(
        Uint8List.fromList(verifiedCiphertext),
        key,
      );
    } catch (_) {
      // Any decoding/decryption failure means no valid message was found
      return null;
    }
  }
}
